-- 006_transaction_logs.sql
-- Immutable transaction / activity audit log

CREATE TABLE IF NOT EXISTS transaction_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  type TEXT NOT NULL CHECK(type IN (
    'deposit_request',
    'deposit_verified',
    'deposit_rejected',
    'deposit_review',
    'balance_credit',
    'balance_debit',
    'card_issued',
    'card_frozen',
    'card_cancelled',
    'card_updated',
    'card_request',
    'card_topup',
    'card_transaction',
    'login',
    'logout',
    'pin_set',
    'pin_reset',
    'otp_sent',
    'otp_verified',
    'biometric_registered',
    'password_changed',
    'support_message',
    'admin_adjustment',
    'other',
    'kyc_submitted',
    'kyc_approved',
    'kyc_rejected',
    'admin_login',
    'admin_bootstrap',
    'admin_role_assigned',
    'admin_role_updated',
    'admin_role_removed',
    'admin_password_set',
    'p2p_ad_created',
    'p2p_ad_cancelled',
    'p2p_buy_order',
    'p2p_buy_order_release',
    'p2p_buy_order_rejected',
    'p2p_sell_order',
    'p2p_sell_order_release',
    'p2p_sell_order_cancelled',
    'p2p_sell_order_rejected',
    'p2p_merchant_escrow_deposit',
    'p2p_merchant_escrow_withdraw',
    'p2p_merchant_escrow_release',
    'p2p_merchant_escrow_credit',
    'escrow_lock',
    'escrow_refund',
    'escrow_release',
    'escrow_receive',
    'internal_transfer_out',
    'internal_transfer_in'
  )),
  direction TEXT DEFAULT 'neutral' CHECK(direction IN ('credit', 'debit', 'neutral')),
  amount_usd REAL,
  amount_mmk REAL,
  balance_before REAL,
  balance_after REAL,
  reference_type TEXT,
  reference_id INTEGER,
  description TEXT NOT NULL,
  metadata TEXT,
  ip_address TEXT,
  created_by TEXT DEFAULT 'system' CHECK(created_by IN (
    'system', 'user', 'admin', 'listener', 'blockchain', 'binance_pay', 'test-bypass', 'tron-indexer'
  )),
  created_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_transaction_logs_user ON transaction_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transaction_logs_type ON transaction_logs(type);
CREATE INDEX IF NOT EXISTS idx_transaction_logs_reference ON transaction_logs(reference_type, reference_id);
